"""add_clause_and_analysis_tables

Revision ID: cd1f7a259c7b
Revises: ed0effae6624
Create Date: 2025-12-09 13:34:29.521891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'cd1f7a259c7b'
down_revision: Union[str, None] = 'ed0effae6624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clause_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_pl', sa.String(length=255), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_pl', sa.Text(), nullable=True),
    sa.Column('default_risk_level', sa.String(length=20), nullable=False),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('clause_count', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("default_risk_level IN ('high', 'medium', 'low')", name='valid_risk_level'),
    sa.ForeignKeyConstraint(['parent_category_id'], ['clause_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('legal_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_code', sa.String(length=100), nullable=False),
    sa.Column('article_title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('law_name', sa.String(length=255), nullable=False),
    sa.Column('jurisdiction', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('official_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_clauses_found', sa.Integer(), nullable=False),
    sa.Column('high_risk_count', sa.Integer(), nullable=False),
    sa.Column('medium_risk_count', sa.Integer(), nullable=False),
    sa.Column('low_risk_count', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_enhanced', sa.Boolean(), nullable=False),
    sa.Column('processing_node', sa.String(length=100), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('offline', 'ai')", name='valid_analysis_mode'),
    sa.CheckConstraint("status IN ('queued', 'processing', 'completed', 'failed', 'cancelled')", name='valid_analysis_status'),
    sa.CheckConstraint('risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)', name='valid_risk_score'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prohibited_clauses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('clause_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('variations', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('embedding', Vector(384), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('detection_accuracy', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("risk_level IN ('high', 'medium', 'low')", name='valid_clause_risk_level'),
    sa.CheckConstraint("source IN ('standard', 'user', 'community', 'imported')", name='valid_clause_source'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='valid_clause_confidence'),
    sa.ForeignKeyConstraint(['category_id'], ['clause_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prohibited_clauses_user_id'), 'prohibited_clauses', ['user_id'], unique=False)
    op.create_table('clause_legal_references',
    sa.Column('clause_id', sa.UUID(), nullable=False),
    sa.Column('legal_reference_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['prohibited_clauses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legal_reference_id'], ['legal_references.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('clause_id', 'legal_reference_id')
    )
    op.create_table('flagged_clauses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('clause_id', sa.UUID(), nullable=True),
    sa.Column('matched_text', sa.Text(), nullable=False),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('start_position', sa.Integer(), nullable=True),
    sa.Column('end_position', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('match_type', sa.String(length=50), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("match_type IN ('keyword', 'vector', 'hybrid', 'ai')", name='valid_match_type'),
    sa.CheckConstraint("risk_level IN ('high', 'medium', 'low')", name='valid_flagged_risk_level'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='valid_flagged_confidence'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clause_id'], ['prohibited_clauses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flagged_clauses')
    op.drop_table('clause_legal_references')
    op.drop_index(op.f('ix_prohibited_clauses_user_id'), table_name='prohibited_clauses')
    op.drop_table('prohibited_clauses')
    op.drop_table('analyses')
    op.drop_table('legal_references')
    op.drop_table('clause_categories')
    # ### end Alembic commands ###
